spring:  
  datasource:  
    url: jdbc:mysql://localhost:3306/beijing12345_db?useSSL=false&serverTimezone=Asia/Shanghai  
    username: root  
    password: csx20040815
    driver-class-name: com.mysql.cj.jdbc.Driver  
  jpa:  
    hibernate.ddl-auto: validate  
    show-sql: true